site_name: Ergate
site_description: FastAPI framework, high performance, easy to learn, fast to code, ready for production
site_url: https://ergate.prryplatypus.dev
docs_dir: docs/docs

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.code.annotate
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    admonition:
      tip: fontawesome/regular/lightbulb

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

nav:
  - Getting started: index.md
  - Tutorial - user guide:
    - basics/creating-an-app.md
    - basics/creating-a-workflow.md
    - basics/jobs-overview.md
    - basics/input-values.md
    - basics/dependencies.md
