site_name: Ergate
site_description: Workflows made easy, your way
site_url: https://ergate.prryplatypus.dev
docs_dir: docs/docs
repo_url: https://github.com/prryplatypus/ergate
repo_name: prryplatypus/ergate
edit_uri: edit/docs/docs/docs/  # edit/<branch>/<folder>

theme:
  name: material
  logo: img/icon.svg
  favicon: img/icon.svg
  custom_dir: docs/overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    # - navigation.tabs
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    admonition:
      tip: fontawesome/regular/lightbulb
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Tutorial - user guide:
    - basics/index.md
    - basics/creating-an-app.md
    - basics/creating-a-workflow.md
    - basics/jobs-overview.md
    - basics/input-values.md
    - basics/dependencies.md
    - basics/user-context.md
    - basics/manual-step-ordering.md
    - basics/workflow-path-hints.md
